apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    run: mongo
---
apiVersion: v1
kind: Pod
metadata:
  name: mongo
  namespace: default
  labels:
    run: mongo
spec:
  volumes:
  - name: mongo-storage
    persistentVolumeClaim:
      claimName: mongo-pvc
  containers:
  - name: mongo
    image: mongo:4.0
    ports:
    - containerPort: 27017
    volumeMounts:
    - mountPath: "/data/db"
      name: mongo-storage